app_config:
  data_import:
    allowed_file_types: 
      - "csv"
    max_file_size: "5MB"
  preprocessing:
    missing_value_strategy: 
      - "mean_imputation"
      - "median_imputation"
      - "remove_rows"
  feature_selection:
    methods: 
      - "recursive_feature_elimination"
      - "LASSO"
      - "random_forest_importance"
  model_selection:
    regression_models: 
      - "linear_regression"
      - "ridge_regression"
      - "lasso_regression"
    classification_models: 
      - "logistic_regression"
      - "random_forest"
      - "support_vector_machine"
  diagnostics:
    metrics: 
      - "RMSE"
      - "R-squared"
      - "Accuracy"
      - "F1-score"